### ISSUE TITLE
Build failure with Boost 1.85.0

### ISSUE THREAD

**Issue by cho-m** [mupen64plus/mupen64plus-video-glide64mk2#128]
mupen64plus fails to build with Boost 1.85.0:
```
  In file included from ../../src/GlideHQ/TxFilterExport.cpp:28:
  In file included from ../../src/GlideHQ/TxFilter.h:29:
  ../../src/GlideHQ/TxHiResCache.h:50:48: error: no type named 'wpath' in namespace 'boost::filesystem'; did you mean 'path'?
    boolean loadHiResTextures(boost::filesystem::wpath dir_path, boolean replace);
                              ~~~~~~~~~~~~~~~~~~~^~~~~
                                                 path
```

According to https://www.boost.org/doc/libs/1_85_0/libs/filesystem/doc/deprecated.html, `typedef basic_path<std::wstring, wpath_traits> wpath` was removed.

It would be good to get a fix in while Boost is still a dependency. Alternatively, removing boost (#46) in a release would resolve this issue.

---

Seen while updating Boost in Homebrew - https://github.com/Homebrew/homebrew-core/pull/169237
